(*The main code inserted by the user and executed associated with the MainTask must be inserted into this POU.*)
PROGRAM UserPrg
VAR
	ON_BUTTON : BOOL;
	LEVEL_SENSOR : BOOL;
	QUALITY_SENSOR : BOOL;
	PRESSURE_SENSOR : BOOL;
	EMERGENCY_BUTTON : BOOL;
	MOTOR : BOOL;
	GREEN_LAMP : BOOL;
	RED_LAMP : BOOL;
	
	SYSTEM_ON : BOOL;
	BUFFER_ON_BUTTON : BOOL;
	TIMER_RED_LAMP : TON;
	TIMER_RED_LAMP_DELAY : TIME := T#500MS;
	TIMER_RED_LAMP_FLAG : BOOL;
	
	TEST_MODE : BOOL := TRUE;
	VIRTUAL_ON_BUTTON : BOOL;
	VIRTUAL_EMERGENCY_BUTTON : BOOL;
END_VAR




//PHYSICAL OR VIRTUAL INPUTS:
ON_BUTTON := I00 OR VIRTUAL_ON_BUTTON;
EMERGENCY_BUTTON := NOT (I04 OR VIRTUAL_EMERGENCY_BUTTON);

IF (TEST_MODE = 0) THEN
	//INPUTS:
	LEVEL_SENSOR := I01;
	QUALITY_SENSOR := I02;
	PRESSURE_SENSOR := I03;
	
	//OUTPUT: 
	Q00 := MOTOR;
	Q01 := GREEN_LAMP;
	Q02 := RED_LAMP;
END_IF; 



//LOGIC:

IF ( ON_BUTTON = 1 ) THEN
	BUFFER_ON_BUTTON := 1;
END_IF

IF ( ON_BUTTON = 0 AND BUFFER_ON_BUTTON = 1 ) THEN		
	SYSTEM_ON := NOT SYSTEM_ON;
	BUFFER_ON_BUTTON := 0;
END_IF

IF ( SYSTEM_ON = 1) THEN
	
	//EMERGENCY STATE!
	IF (EMERGENCY_BUTTON = 1) THEN
		SYSTEM_ON := 0;
	END_IF;	
	
	MOTOR := LEVEL_SENSOR = 1 AND QUALITY_SENSOR = 1 AND 
			 PRESSURE_SENSOR = 0;	
	GREEN_LAMP := MOTOR;
	
	IF ( MOTOR = 0) THEN
		TIMER_RED_LAMP(IN:=TIMER_RED_LAMP_FLAG, PT:=TIMER_RED_LAMP_DELAY);
		
		IF (TIMER_RED_LAMP.Q = 1) THEN
			RED_LAMP := NOT RED_LAMP;
			TIMER_RED_LAMP_FLAG := 0;
		ELSE
			TIMER_RED_LAMP_FLAG := 1;
		END_IF
	//MOTOR IS RUNNING:
	ELSE 
		RED_LAMP := 0;	
	END_IF	

//SYSTEM OFF
ELSE 
	MOTOR := 0;
	GREEN_LAMP := 0;
	RED_LAMP := EMERGENCY_BUTTON;
END_IF