(*The main code inserted by the user and executed associated with the MainTask must be inserted into this POU.*)
PROGRAM UserPrg
VAR
	ON_BUTTON : BOOL;
	BAR_SENSOR : BOOL;
	WINDOW1_SENSOR : BOOL;
	WINDOW2_SENSOR : BOOL;
	KITCHEN_SENSOR : BOOL;
	GARAGE_SENSOR : BOOL;
	ROOM_SENSOR : BOOL;
	HALL_SENSOR : BOOL;
	ALARM : BOOL;
	
END_VAR



IF (ON_BUTTON = 1) THEN
	IF (BAR_SENSOR = 0 OR WINDOW1_SENSOR = 0 OR 
		WINDOW2_SENSOR = 0 OR ROOM_SENSOR = 1 OR
		GARAGE_SENSOR = 1 OR KITCHEN_SENSOR = 1 OR 
		HALL_SENSOR = 1) THEN
		
		ALARM := 1;
	 END_IF
ELSE 
	ALARM := 0;
END_IF


//I/OS
ON_BUTTON := ON_BUTTON_INPUT;
BAR_SENSOR := BAR_SENSOR_INPUT;
WINDOW1_SENSOR := WINDOW1_SENSOR_INPUT;
WINDOW2_SENSOR := WINDOW2_SENSOR_INPUT;
ROOM_SENSOR := ROOM_SENSOR_INPUT;
KITCHEN_SENSOR := KITCHEN_SENSOR_INPUT;
HALL_SENSOR := HALL_SENSOR_INPUT;
GARAGE_SENSOR := GARAGE_SENSOR_INPUT;
ALARM_OUTPUT := ALARM;


