(*The main code inserted by the user and executed associated with the MainTask must be inserted into this POU.*)
PROGRAM UserPrg
VAR
	ON_BUTTON : BOOL;
	MOTOR : BOOL;
	PRESSURE_SENSOR : BOOL;
	LAMP : BOOL;
	MOTOR_SIGNAL : BOOL;
	SYSTEM_ON : BOOL;
	BUFFER_ON_BUTTON : BOOL;
	MOTOR_TIMEOUT : TON;
	MOTOR_TIMEOUT_DELAY : TIME := T#5S;
	ALARM_STATE : BOOL;
END_VAR



//I-O'S:
ON_BUTTON := I00;
PRESSURE_SENSOR := I01;
MOTOR_SIGNAL := I02;
Q00 := MOTOR;
Q01 := LAMP;

MOTOR_TIMEOUT(IN := MOTOR, PT := MOTOR_TIMEOUT_DELAY);


IF (ON_BUTTON = 1) THEN
	BUFFER_ON_BUTTON := 1;
END_IF

IF ( ON_BUTTON = 0 AND BUFFER_ON_BUTTON = 1) THEN
	SYSTEM_ON := NOT SYSTEM_ON;
	BUFFER_ON_BUTTON := 0;
END_IF

//MOTOR := SYSTEM_ON = 1 AND PRESSURE_SENSOR = 1;
//LAMP := SYSTEM_ON = 1 AND MOTOR_SIGNAL = 1;

IF ( SYSTEM_ON = 1 ) THEN
	
	MOTOR := PRESSURE_SENSOR AND ALARM_STATE = 0;	
	LAMP := MOTOR_SIGNAL;
	
	IF (MOTOR = 1 AND MOTOR_SIGNAL = 0 AND MOTOR_TIMEOUT.Q = 1) THEN
		ALARM_STATE := 1;
	END_IF
	
	//IF ( PRESSURE_SENSOR = 1 ) THEN
	//	MOTOR := 1;
	//ELSE
	//	MOTOR := 0;
	//END_IF
	
	//IF ( MOTOR_SIGNAL = 1 ) THEN
	//	LAMP := 1;
	//ELSE
	//	LAMP := 0;
	//END_IF	

ELSE //SISTEMA DESLIGADO:
	MOTOR := 0;
	LAMP := 0;		
END_IF